#+TITLE: Hasta_el_hueso_e P23
* EP21 [[https://archive.org/details/hasta-el-hueso-23-midiendo-tugurios][archive.org]]


****** Lukas Jaramillo:  Arquitectura a escala humana, de los poros.
****** Carlos Alberto Montoya (Arquitecto):  el habitar es el ejercicio del hombre
****** CM: la vivienda tiene poder para movilizar fuerzas positivas
****** CM: medellin no tiene suelo, se invade porque encuentran el suelo
****** CM: el más recursivo es el que tiene menos
****** Marta Pelaez: ¿El gobierno de turno es el adecuado para amplificar las invitaciones de las letras del reggetón en un evento de prevención de embarazo?
****** MP:  No hubo programa "salas abiertas"
****** CM: el poder que tiene la vivienda para acercar el gobierno a su población
******  LJ: No puede haber espacio público si no hay vivienda, para que parque si no tengo casa

****** Nana: la casa para guardar los sueños, guardar un futuro, donde guardarse, un día bien pelle ¿dónde vas? el abrigo de un lugar.
****** ??:  el resguardo
****** LJ: el aposento
****** ??: en arriendo es difícil pensar en como apropiarse de el espacio.

****** LJ: un desplazado es un pacifista, "yo no me voy a sumar a esta guerra, hágale, yo me voy",  dignidad de dar la vuelta y decir: "me voy pues..."

****** Nana: Deapegarse de lo propio, al llegar a la ciudad se enfrenta a la interperie de una ciudad que lo ignora.

****** LJ: Las piezas de hierro se hacen con moldes de madera

****** ??: estar en la calle no es por que le gusta, encuentran unas prácticas que le  interesan y unos riesgos que esta dispuesto a asumir.

****** LJ: una ciudad donde la vivienda de interés social no sea negocio
